@startuml
left to right direction
class Compiler


class Token
Token : - tokenId : TokenId
Token : - literal : String
Token : - val : Value
Token : + integer : int
Token : + bigInteger : BigInteger
Token : + character : char
Token : + string : String
Token : - parse() : void
Token : + getTokenId() : TokenId
Token : + equals(Object o) : boolean
Token : + hashCode() : int
Token : + toString() : String


